version: '3.8'

services:
  nodix:
    build: .
    container_name: nodix-unix
    command: ["bun", "run", "test"]
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
